### ISSUE TITLE
cannot run make_dataframe.py

### ISSUE THREAD

**Issue by daquang** [jambo6/physionet_sepsis_challenge_2019#1]
I'm trying to make the dataframe from the raw files, but I am missing the following file:

DATA_DIR + '/interim/from_raw/df.pickle'

**Comment by jambo6** [comment]
Hello, 

That's strange, that file shouldn't exist anymore. Can you try pulling from master and running it again? Let me know if that works. 

Best, 
James

**Comment by daquang** [comment]
Still getting the same error.

It's this line:

`df = load_pickle(DATA_DIR + '/interim/from_raw/df.pickle')`

Was I supposed to run a script before running make_dataframe.py?

**Comment by jambo6** [comment]
Ah I apologise, I have got a bit confused, I made a new repository with updated code that's here:

-->  https://github.com/jambo6/sepsis_competition_physionet_2019

I would recommend using this one instead. I seem to have messed this one up and will remove it!
